### ISSUE TITLE
TypeError: Cannot read property 'fileParser' of undefined

### ISSUE THREAD

**Issue by waltergms** [laoqiren/mlhelper#1]
```
const mlTool = require('mlhelper').utils.fileParser;

let dt = parser.read_csv(path.join(__dirname, './Pasta1.csv'), {
	index_col: 0,
	delimiter: ',',
	header: 0,
	dataType: 'number'
});
let labels = dt.getClasses();
let dataSet = dt.drop('quality').values;

const charts = require('mlhelper').utils.charts;
let knn = new kNN(dataSet, labels);
let inx = [7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8],
	normalInx = knn.autoNormalVector(inx);

console.log(knn.classify(inx, 100)); // 6
charts.drawkNN(kNN.autoNormal(dataSet), labels, normalInx, {
	width: "500px",
	height: "400px",
	size: 15
});
```

Debugger listening on ws://127.0.0.1:6834/598e84f2-6fdf-48e9-bfb2-3ec0d8c90f79
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:7272) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprec
ated. Please use `node --inspect-brk` instead.
C:\Users\walter.silva\Documents\Visual Studio 2017\Projects\NodejsConsoleApp17\a
pp.js:1
(function (exports, require, module, __filename, __dirname) { const mlTool = req
uire('mlhelper').utils.fileParser;

                      ^

TypeError: Cannot read property 'fileParser' of undefined
    at Object.<anonymous> (C:\Users\walter.silva\Documents\Visual Studio 2017\Pr
ojects\NodejsConsoleApp17\app.js:1:103)
    at Module._compile (module.js:621:14)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Waiting for the debugger to disconnect...

**Comment by laoqiren** [comment]
@waltergms Thanks for you test.  This is a bug, and I have fixed this issue just now,  you can update `mlhelper`  using `npm update mlhelper` . You can still use the old version but you have to get `utils` and `algorithm` like this: 
`const parser = require('mlhelper').default.utils.fileParser`

 Really thanks for your test and report.

**Comment by waltergms** [comment]
```
const parser = require('mlhelper').utils.fileParser;

let dt = parser.read_csv(path.join(__dirname, './Pasta1.csv'), {
	index_col: 0,
	delimiter: ',',
	header: 0,
	dataType: 'number'
});
```
```
Debugger listening on ws://127.0.0.1:35992/8ec1f545-0f3f-43e5-ae87-113d3446c0bd
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:7408) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprec
ated. Please use `node --inspect-brk` instead.
C:\Users\walter.silva\Documents\Visual Studio 2017\Projects\NodejsConsoleApp17\a
pp.js:3
let dt = parser.read_csv(path.join(__dirname, './Pasta1.csv'), {
                ^

TypeError: Cannot read property 'read_csv' of undefined
    at Object.<anonymous> (C:\Users\walter.silva\Documents\Visual Studio 2017\Pr
ojects\NodejsConsoleApp17\app.js:3:17)
    at Module._compile (module.js:621:14)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Waiting for the debugger to disconnect...
```
Now utils are accessible, but fileParser dont...

**Comment by laoqiren** [comment]
@waltergms Thanks, try again now.
